package com.example.data.export

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.example.model.CaptionSegment
import com.example.util.TimeUtils
import java.io.File

object SubtitleExporter {

    fun generateSrtContent(captions: List<CaptionSegment>): String {
        val sb = StringBuilder()
        val sorted = captions.sortedBy { it.startMs }
        for ((index, cue) in sorted.withIndex()) {
            sb.append("${index + 1}\n")
            sb.append("${TimeUtils.formatSrtTime(cue.startMs)} --> ${TimeUtils.formatSrtTime(cue.endMs)}\n")
            sb.append("${cue.text.trim()}\n\n")
        }
        return sb.toString()
    }

    fun generateVttContent(captions: List<CaptionSegment>): String {
        val sb = StringBuilder()
        sb.append("WEBVTT - Generated by UrduSub\n\n")
        val sorted = captions.sortedBy { it.startMs }
        for ((index, cue) in sorted.withIndex()) {
            sb.append("${index + 1}\n")
            sb.append("${TimeUtils.formatVttTime(cue.startMs)} --> ${TimeUtils.formatVttTime(cue.endMs)}\n")
            sb.append("${cue.text.trim()}\n\n")
        }
        return sb.toString()
    }

    fun exportToFile(context: Context, filename: String, content: String): File {
        val exportDir = File(context.cacheDir, "exports").apply { mkdirs() }
        val file = File(exportDir, filename)
        file.writeText(content, Charsets.UTF_8)
        return file
    }
}
